---
language: python
python: "3.8.6"
sudo: required

env:
  - ansible_version: 2.8.8

services:
  - docker

install:
  - pip3 install pipenv
  - pipenv install ansible==${ansible_version}
  - pipenv install -r test-requirements.txt
script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
