---
language: python
python: "3.8.6"
sudo: required

services:
  - docker

install:
  - pip3 install pipenv
  - pipenv sync
script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
