---

- name: Airflow | Ensure Airflow group
  group:
    name: "{{ airflow_group }}"

- name: Airflow | Ensure Airflow user
  user:
    name: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    shell: /bin/bash

- name: Airflow | Create path for Airflow home
  file:
    path: "{{ airflow_home }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Create path for configuration files
  file:
    path: "{{ airflow_environment_file_folder }}"
    state: directory
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Installing dependencies
  apt:
    pkg: "{{ airflow_required_libs }}"
    state: present
    update_cache: yes

- name: Airflow | Installing Python pip dependencies
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ airflow_required_python_packages }}"

- name: Airflow | Installing proper Celery version
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: celery
    version: "{{ celery_version }}"
  when: airflow_executor == "CeleryExecutor"

- name: Airflow | Installing extra Celery packages
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: celery[{{ item }}]
    version: "{{ celery_version }}"
  with_items: "{{ celery_extra_packages }}"
  when: airflow_executor == "CeleryExecutor" and celery_extra_packages

- name: Airflow | Set AIRFLOW_HOME environment variable in /etc/environment
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME={{ airflow_home }}'

- name: AIRFLOW | Check airflow version
  shell: '[ -x "$(command version airflow)" ] && echo "True" || echo "False"'
  register: airflow_check_command
  changed_when: false
  ignore_errors: true
  become: yes
  become_user: "{{ airflow_user }}"

- name: AIRFLOW | Set installed fact
  set_fact:
    airflow_check: "{{ airflow_check_command.stdout }}"

- name: Airflow | Installing Airflow
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: apache-airflow
    version: "{{ airflow_version }}"
    extra_args: --no-cache-dir
  register: airflow_install
  environment:
    SLUGIFY_USES_TEXT_UNIDECODE: "yes"
  when:
    - not airflow_check

- name: Airflow | Installing Airflow Extra Packages (prior to Ansible 2.7)
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: "apache-airflow[{{ item }}]=={{ airflow_version }}"
  with_items: "{{ airflow_extra_packages }}"
  when:
    - airflow_extra_packages
    - ansible_version.full is version_compare('2.7', '<')

- name: Airflow | Installing Airflow Extra Packages
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: "apache-airflow[{{ airflow_extra_packages | join(', ') }}]"
    version: "{{ airflow_version }}"
  when:
    - airflow_extra_packages
    - ansible_version.full is version_compare('2.7', '>=')
    - not airflow_install_use_constraints

- name: Airflow | Installing Airflow Extra Packages With Constraints
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: "apache-airflow[{{ airflow_extra_packages | join(', ') }}] {{ airflow_extra_packages_constraints }}"
    version: "{{ airflow_version }}"
  when:
    - airflow_extra_packages
    - ansible_version.full is version_compare('2.7', '>=')
    - airflow_install_use_constraints

- name: Airflow | Installing DAGs dependencies
  pip:
    executable: "{{ airflow_pip_executable }}"
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ dags_dependencies }}"
  when: dags_dependencies
  notify:
    - restart airflow-webserver
    - restart airflow-scheduler
    - restart airflow-worker
    - restart airflow-flower

- name: Airflow | Copy Environment File
  template:
    src: airflow-environment-file.j2
    dest: "{{ airflow_environment_file_folder }}/airflow"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: Airflow | Copy Daemon scripts
  template:
    src: "{{ item.key }}.service.j2"
    dest: /lib/systemd/system/{{ item.key }}.service
    mode: 0644
  notify: restart {{ item.key }}
  with_dict: "{{ airflow_services }}"
  when: item.value.enabled
