---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .

platforms:
  - name: airflow-${MOLECULE_DISTRO:-buster}
    image: debian:${MOLECULE_DISTRO:-buster}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    groups:
      - airflow
    tmpfs:
      - /redis
      - /tmp:exec
      - /run
      - /run/lock
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:${AIRFLOW_WEBSERVER_PUBLISHED_PORT:-8080}:8080/tcp
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
