---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: airflow_extra_packages-${MOLECULE_DISTRO:-buster}
    image: debian:${MOLECULE_DISTRO:-buster}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - /tmp:exec
      - /run
      - /run/lock
    groups:
      - airflow
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: extra_packages
verifier:
  name: ansible